FROM node:10.16.3

LABEL version="1.1"
LABEL description="ConnectionClient"

RUN mkdir -p /srv/app/connection-client
WORKDIR /srv/app/connection-client

COPY package*.json /srv/app/connection-client/
RUN npm cache clean --force && npm install

COPY . /srv/app/connection-server/

EXPOSE 3000

CMD [ "npm", "run", "start"]