version: "3"
services:
  #********************************************
  #*****  Client Container
  #********************************************
  client:
    container_name: connection-client
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - "./client/src:/srv/app/connection-client/src"
      - "./client/public:/srv/app/connection-client/public"
    links:
      - server
    command: npm run start
  #********************************************
  #*****  Node Container
  #********************************************
  server:
    build: .
    container_name: connection-server
    expose:
      - ${APP_SERVER_PORT}
    env_file:
      - .env
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    volumes:
      - "./:/srv/app/connection-server"
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    depends_on:
      - db
  #********************************************
  #*****  Mongodb Container
  #********************************************
  db:
    container_name: db
    image: mongo:3.6-xenial
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ../../../../var/lib/mongodb:/data/db
